### ISSUE TITLE
metricsets including NaN values rejected

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-agent-dotnet#589] opened 2019-11-09 14:50 UTC
**Describe the bug**
.NET agent producing invalid metricset payloads, apparently due to inclusion of `NaN` values.

**To Reproduce**
Per [this discuss issue](https://discuss.elastic.co/t/apm-dotnet-1-1-2-error-validating-json-document-against-schema-i-s-doesnt-validate-with-metricset/207101), run on a system where system process cpu isn't available?

**Expected behavior**
Omit `NaN` values.

**Comment by vhatsura** [comment] 2019-11-20 15:36
@SergeyKleyman, I think the issue can be closed

**Comment by SergeyKleyman** [comment] 2019-11-20 15:47
#590 provides a workaround by essentially discarding metrics that current implementation cannot provide (calculations result in NaN, etc.)

We still don't know what is root cause for this issue but since we don't officially support AWS Lambda for .NET agent yet I will close this issue for now and we will revisit it when we start working on supporting AWS Lambda.

**Closed by SergeyKleyman** 2019-11-20 15:47 UTC
Labels: bug
