### ISSUE TITLE
[META 745] Implement Azure Functions metadata detection

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-dotnet#1974] opened 2023-01-13 07:25 UTC
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/745

**Comment by z1c0** [comment] 2023-01-13 07:41
Duplicate of (implemented in) https://github.com/elastic/apm-agent-dotnet/issues/1642

**Closed by z1c0** 2023-01-13 07:41 UTC
Labels: agent-dotnet
