### ISSUE TITLE
When the request body is added for .net core?

### ISSUE THREAD

**Issue by brezaie** [elastic/apm-agent-dotnet#435] opened 2019-08-07 07:10 UTC
Do you any plans to add the request body to the .net core configuration?

**Comment by SergeyKleyman** [comment] 2019-08-07 07:51
Hi @brezaie.
First of all thank you for trying out the agent.

Second - a small administrative issue. As mentioned in [README](https://github.com/elastic/apm-agent-dotnet/blob/master/README.md) we recommend using [the forum](https://discuss.elastic.co/tags/c/apm/dotnet) for questions and GitHub issues for confirmed bugs and enhancement requests. The forum allows other users to learn from the questions and answers and the number of people that can answer a question at the forum is much larger than at the Github repo which is mostly for developers of the agent.

Regarding your question - there is already a PR in progress - #402. I assume the feature will be implemented soon (we don't commit on any specific dates).

Please let us know if the above answers your question and if the issue can be closed.

**Comment by SergeyKleyman** [comment] 2019-08-13 11:40
@brezaie I'm going to close this issue as duplicate of #213. If you have any further concerns regarding this issue please let us know.

**Closed by SergeyKleyman** 2019-08-13 11:40 UTC
