### ISSUE TITLE
Logs not transferred gracefully upon application shutdown...

### ISSUE THREAD

**Issue by nvrnight** [elastic/apm-agent-dotnet#693] opened 2020-01-17 22:05 UTC
**Describe the bug**

**To Reproduce**
1. Use this config '...'
ELASTIC_APM_FLUSH_INTERVAL  = 0
2. Then call '....'
Agent.Setup(new AgentComponents());
3. Then do '....'
Agent.Tracer.CaptureTransaction("foo", "bar", () => {
     Thread.Sleep(1000);
});
I'm setting up logging for a console application using the above settings, it shuts down before the transaction is sent to the APM server. I tested with a while(true) {}) at the end and the transaction is logged eventually. This is problematic because if I use this in a long-lived application, that means if I have to shutdown the application, the remaining transactions will not be flushed/logged and the data will be lost.

**Expected behavior**
The agent to flush its logs upon application shutdown, maybe using IDisposable with the ApmAgent some how?

**Comment by gregkalapos** [comment] 2020-01-18 16:36
This is kind of a duplicate of https://github.com/elastic/apm-agent-dotnet/issues/288.

Definitely something we plan to address.

**Closed** 2020-02-03 19:30 UTC
Labels: bug

**Comment by mathis-m** [comment] 2020-07-25 18:07
Have a look at my PoC on how to integrate into .Net Core Console Application.
I implemented FlushQueue mehtod extension on IApmAgent.
