### ISSUE TITLE
[BUG] Can't publish .NET Core after updating Elastic.Apm.NetCoreAll to V 1.27.1

### ISSUE THREAD

**Issue by guisantos** [elastic/apm-agent-dotnet#2367] opened 2024-05-28 12:12 UTC
### APM Agent version
Elastic.Apm..NetCoreAll v 1.27.1

### Environment
.NET Core 6
Windows 11

**Application Target Framework(s)** (e.g. net462, netcoreapp3.1):
net6.0

### Describe the bug
After updating Elastic.Apm..NetCoreAll from Version 1.25.0 to 1.27.1 a dependency to MongoDB.Driver.Core is added and a transitive dependency to MongoDB.Driver.Core called zstdsharp.port.
The error happen when you try to publish the API solution to a folder.

### To Reproduce

1. Create a .net 6 solution
2. Install Elastic.Apm.NetCoreAll V 1.27.1
3. Create a new publish to a folder using the following configurations:
![image](https://github.com/elastic/apm-agent-dotnet/assets/14335913/67f688f9-b12b-4666-9c72-3ce655f1926c)
4. Publish the solution
5. See error in the output window

Try to to publish the application and you will receive the following error:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		System.AggregateException: One or more errors occurred. (Code generation failed for method '[ZstdSharp]ZstdSharp.Unsafe.Methods.ZSTD_cwksp_move(ZSTD_cwksp*,ZSTD_cwksp*)')	ObiAPI.Api		0	
> Error		Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being optimized, or set the PublishReadyToRun property to false.	ObiAPI.Api		0	
> Error		Error: One or more errors occurred. (Code generation failed for method '[ZstdSharp]ZstdSharp.Unsafe.Methods.ZSTD_cwksp_move(ZSTD_cwksp*,ZSTD_cwksp*)')	ObiAPI.Api		0	
> Error		at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)	ObiAPI.Api		0	
> Error		at System.Threading.Tasks.TaskReplicator.Replica.Execute()	ObiAPI.Api		0	
> Error		at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)	ObiAPI.Api		0	
> Error		at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)	ObiAPI.Api		0	
> Error		at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)	ObiAPI.Api		0	
> Error		at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)	ObiAPI.Api		0	
> Error		at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)	ObiAPI.Api		0	
> Error		at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)	ObiAPI.Api		0	
> Error		at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)	ObiAPI.Api		0	
> Error		at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)	ObiAPI.Api		0	
> Error		at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)	ObiAPI.Api		0	
> Error		at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL)	ObiAPI.Api		0	
> Error		at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger)	ObiAPI.Api		0	
> Error		at ILCompiler.ReadyToRunCodegenCompilation.ComputeDependencyNodeDependencies(List`1 obj)	ObiAPI.Api		0	
> Error		at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile)	ObiAPI.Api		0	
> Error		at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__36_0(DependencyNodeCore`1 dependency)	ObiAPI.Api		0	
> Error		at ILCompiler.Program.RunSingleCompilation(Dictionary`2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary`2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)	ObiAPI.Api		0	
> Error		at ILCompiler.Program.Run(String[] args)	ObiAPI.Api		0	
> Error		at ILCompiler.Program.Main(String[] args)	ObiAPI.Api		0	
> Error		at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()	ObiAPI.Api		0	
> Error		---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[ZstdSharp]ZstdSharp.Unsafe.Methods.ZSTD_cwksp_move(ZSTD_cwksp*,ZSTD_cwksp*)'	ObiAPI.Api		0	
> Error		--- End of stack trace from previous location ---	ObiAPI.Api		0	
> Error		--- End of stack trace from previous location ---	ObiAPI.Api		0	
> Error		--- End of inner exception stack trace ---	ObiAPI.Api		0	

#### Expected behavior
DLLs and project dependencies publish to a folder

#### Actual behavior
Impossible to publish the project

**Comment by stevejgordon** [comment] 2024-06-03 07:40
Hi, @guisantos.

`Elastic.Apm.NetCoreAll` has always had a dependency on `MongoDB.Driver.Core`. In [v1.25.3](https://github.com/elastic/apm-agent-dotnet/releases/tag/v1.25.3), we updated the minimum supported dependency to 2.19.0 (from 2.4.4) due to a [CVE](https://security.snyk.io/vuln/SNYK-DOTNET-MONGODBDRIVER-3329316). 

ReadyToRun publishing fails here because the `ZstdSharp` library uses code that is not AoT compatible. This is not a bug, simply a limitation of that library. 

In your case, you can either publish without ReadyToRun or, if you do not require the MongoDB instrumentation, install the `Elastic.Apm` package and any instrumentation packages you require and see if that works. Note, though, that we do not test the libraries for AoT and do not support that as some of our code relies on reflection, etc., which is likely to fail AoT compilation.

**Comment by guisantos** [comment] 2024-06-04 11:55
Oh, thanks @stevejgordon I'm was doing some cleanup and updates on references and this concerned me, I will do as you suggested using the Elastc.Apm package and add the instrumentations manually, I don't even need the mongodb stuff

**Comment by stevejgordon** [comment] 2024-06-27 07:53
Closing as resolved.

**Closed by stevejgordon** 2024-06-27 07:53 UTC
Labels: bug, community
