### ISSUE TITLE
Unable to show database trace with Elastic.Apm.AspNetFullFramework

### ISSUE THREAD

**Issue by tyienyien** [elastic/apm-agent-dotnet#796] opened 2020-03-29 14:15 UTC
**Describe the bug**
Elastic.Apm.AspNetFullFramework not showing database calls at Kibana
Similar to the issue https://www.gitmemory.com/issue/elastic/apm-agent-dotnet/700/576692294
I am using entity framework version 6.2.0 with oracle.

**To Reproduce**
1. Added the DbInterceptor at global.asax.cs but still not working
			DbInterception.Add(new Elastic.Apm.EntityFramework6.Ef6Interceptor());

2. I am using .net framework 4.6.1, entityframework version 6.2.1 and Elastic.APM.AspNetFullFramework version 1.4.0
Elastic.Apm.EntityFramework6 version 1.4.0

3. I am trying to do some web api call, I can see my api call at kibana APM but not the database tracer.  Already enable the database tracer, 
Following exactly the following page
https://github.com/elastic/apm-agent-dotnet/blob/master/docs/setup.asciidoc
but still not luck.

**Comment by gregkalapos** [comment] 2020-03-30 14:02
@tyienyien the best way to troubleshoot this would be probably to turn on logging.

[Here](https://github.com/elastic/apm-agent-dotnet/blob/master/sample/AspNetFullFrameworkSampleApp/App_Start/LoggingConfig.cs#L56) is an example on how to direct logs from the agent to NLog - in case you already have a logging system in use, you can do something similar - if not I'd say the best is to just copy-paste that into your app and use NLog.

Once that's done you can set the log level to `Trace` and paste the logs here - that'll help me to figure out what's going on.

Alternatively - if it's possible to link a small reproducer I can also take a look at that.

**Comment by tyienyien** [comment] 2020-03-31 06:25
Hi @gregkalapos,
Thanks a lot for the logging.  I have now able the see some errors here.

First error:
Failed instantiating PerformanceCounter - please make sure the current user has permissions to read performance counters. E.g. make sure the current user is member of the 'Performance Monitor Users' group
+-> Exception: System.UnauthorizedAccessException: Access to the registry key 'Global' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalGetValue(String name, Object defaultValue, Boolean doNotExpand, Boolean checkSecurity)
   at Microsoft.Win32.RegistryKey.GetValue(String name)
   at System.Diagnostics.PerformanceMonitor.GetData(String item)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)
   at Elastic.Apm.Metrics.MetricsProvider.SystemTotalCpuProvider..ctor(IApmLogger logger)

Second error:

TraceEventSession initialization failed - GC metrics won't be collected
+-> Exception: System.UnauthorizedAccessException: Error Starting ETW:  Access Denied (Administrator rights required to start ETW)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.InsureStarted(EVENT_TRACE_PROPERTIES* properties)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableProvider(Guid providerGuid, TraceEventLevel providerLevel, UInt64 matchAnyKeywords, TraceEventProviderOptions options)
   at Elastic.Apm.Metrics.MetricsProvider.GcMetricsProvider.<.ctor>b__15_0()

Third error:
Processing of DB-operation-ended event failed
+-> Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Elastic.Apm.Model.DbSpanCommon.GetDestination(String dbConnectionString, Boolean isEmbeddedDb, Nullable`1 defaultPort)
   at Elastic.Apm.Model.DbSpanCommon.EndSpan(Span span, IDbCommand dbCommand, Nullable`1 duration)
   at Elastic.Apm.EntityFramework6.Ef6Interceptor.Impl.DoEndSpan[TResult](IDbCommand command, DbCommandInterceptionContext`1 interceptCtx, String dbgOriginalCaller)
   at Elastic.Apm.EntityFramework6.Ef6Interceptor.Impl.EndSpan[TResult](IDbCommand command, DbCommandInterceptionContext`1 interceptCtx, String dbgCaller)
2020-03-31 13:52:36.215 +08:00 | TRACE | 9                              | {Ef6Interceptor.Impl#E82561} DB operation ended - ending the corresponding span... DbCommandInterceptionContext: #158C32 Caller: ReaderExecuted. Statement: SELECT

**Comment by gregkalapos** [comment] 2020-04-01 17:15
Thank you for the logs @tyienyien, very useful! 


Based on this part of the log:

```
| {Ef6Interceptor.Impl#3C3E89E} Processing of DB-operation-ended event failed
+-> Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at Elastic.Apm.Model.DbSpanCommon.GetDestination(String dbConnectionString, Boolean isEmbeddedDb, Nullable1 defaultPort) at Elastic.Apm.Model.DbSpanCommon.EndSpan(Span span, IDbCommand dbCommand, Nullable1 duration)
at Elastic.Apm.EntityFramework6.Ef6Interceptor.Impl.DoEndSpan[TResult](IDbCommand command, DbCommandInterceptionContext1 interceptCtx, String dbgOriginalCaller) at Elastic.Apm.EntityFramework6.Ef6Interceptor.Impl.EndSpan[TResult](IDbCommand command, DbCommandInterceptionContext1 interceptCtx, String dbgCaller)
```

this looks to me that this is something that just got fixed by @SergeyKleyman in #795 - in #791 we had the same issue I feel - that also happened with oracle.

@SergeyKleyman could you please take a quick look and see if you also think this is fixed?

@tyienyien: if you give us your connection string we could also add that to our tests (feel free to trim any sensitive infos (especially username and password) - we are only interested in the structure of the connection string so we can run it through our parsing logic).

**Comment by SergeyKleyman** [comment] 2020-04-02 06:44
> @SergeyKleyman could you please take a quick look and see if you also think this is fixed?

Yes, it looks that `NullReferenceException` source is the same as in #791 so #795 should fix that part.
If DB connection string here has the same structure as the one in #791 then #795 should fix that part as well. But even if DB connection parsing fails, after #795 it should not prevent DB spans from being ended.

**Comment by gregkalapos** [comment] 2020-04-02 14:02
> > @SergeyKleyman could you please take a quick look and see if you also think this is fixed?
> 
> Yes, it looks that `NullReferenceException` source is the same as in #791 so #795 should fix that part.
> If DB connection string here has the same structure as the one in #791 then #795 should fix that part as well. But even if DB connection parsing fails, after #795 it should not prevent DB spans from being ended.

Great! Ok, so this is very likely fixed and will be included in the next release.

Closing now.

@tyienyien if we get a connection string we can verify and add that to our test - you can just follow up here if you feel so.

**Closed by gregkalapos** 2020-04-02 14:02 UTC
Labels: bug

**Comment by tyienyien** [comment] 2020-04-06 09:03
@gregkalapos and @SergeyKleyman ,

Here is my database connection string
 <add name="default" providerName="Oracle.ManagedDataAccess.Client" connectionString="Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=DATABASENAME)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DATABASESERVICENAME))); User ID=USERNAME; password=PASSWORD; Pooling=False"/>

**Comment by gregkalapos** [comment] 2020-04-07 19:51
Thank @tyienyien - in #815 I added the connection string - all looks good, the test is green with it, so the agent will be able to parse it in the next release. 

To your question regarding the stack trace: that's because in that case you only have a transaction - there is no span captured there. Stack trace is only captured for spans, so you'll need a span in that request. One option would be to start one with the [Public Agent API](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html).

**Comment by tyienyien** [comment] 2020-04-09 02:58
Hi @gregkalapos ,

I will try the span in one of my API and try it out.
Thanks for your reply.
