### ISSUE TITLE
Following events were not transferred successfully to the server 

### ISSUE THREAD

**Issue by e-jlion** [elastic/apm-agent-dotnet#1282] opened 2021-04-29 02:56 UTC
Please use the [discuss forum](https://discuss.elastic.co/c/apm) to ask questions.
warn: Elastic.Apm[0]
{PayloadSenderV2} Failed sending events. Following events were not transferred successfully to the server (http://goodly-kiwi-apm-server.prod-web.svc.cluster.local:8200/):
Transaction{Id: 448aab3d34107d4f, TraceId: f9cef7d03cd5dd4bbde50de6cce23399, ParentId: null, Name: /grpc.health.v1.Health/Check, Type: request, Outcome: Success, IsSampled: False},
Transaction{Id: 4bdb37edd360694b, TraceId: 4409302add693445abe0cca714c6d379, ParentId: null, Name: /Yalla.Pic.Service.Grpc.PicService/Heartbeat, Type: request, Outcome: Success, IsSampled: False},
Transaction{Id: e5ccdda7cd2dcc48, TraceId: b99ad67418efd6498145c42e4f3ad6c0, ParentId: null, Name: /grpc.health.v1.Health/Check, Type: request, Outcome: Success, IsSampled: False},
Transaction{Id: f41eed5b3caeb148, TraceId: 9b4ea735bc674e4dae1f2b35045f89e2, ParentId: null, Name: /grpc.health.v1.Health/Check, Type: request, Outcome: Success, IsSampled: False},
Transaction{Id: a5a569a2e522ad4e, TraceId: fad1cee98954c4498b5a19d33ed02f53, ParentId: null, Name: /grpc.health.v1.Health/Check, Type: request, Outcome: Success, IsSampled: False}
System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: The response ended prematurely.
at System.Net.Http.HttpConnection.FillAsync(Boolean async)
at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.DiagnosticsHandler.

**Comment by russcam** [comment] 2021-04-29 04:57
@e-jlion The exception is

```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: The response ended prematurely.
```

This means APM server to which you were making an HTTP request closed the connection without having sent back a complete response. The root cause is often something else; If you debug, and inspect the exception, there may be an inner exception which should provide more detail on what the root cause is.

**Comment by gregkalapos** [comment] 2021-06-01 12:30
@e-jlion did you manage to get this work? Can we close this? I feel there isn't much we can do here right now.

**Comment by e-jlion** [comment] 2021-06-02 07:25
> @e-jlion did you manage to get this work? Can we close this? I feel there isn't much we can do here right now.

you can close this ，think you

**Closed** 2021-06-02 08:10 UTC
Labels: agent-dotnet
