### ISSUE TITLE
Support For IgnoreUrls Property In appsettings.json

### ISSUE THREAD

**Issue by PBarnard** [elastic/apm-agent-dotnet#903] opened 2020-07-14 11:10 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to be able to filter out Kubernetes readiness and health probe requests in APM via the IgnoreUrls property present for other languages like the Java and Node implementations.

**Describe the solution you'd like**
It would be ideal to be able to specify an array of URLs to ignore in the APM configuration section of appsettings.json:

`
"ElasticApm": {
    "IgnoreUrls": [
        "/health/ping1",
        "/health/ping2"
    ]
}
`

**Describe alternatives you've considered**
As suggested by @SergeyKleyman in a support ticket, I'll use the Filter API as a workaround.

**Comment by gregkalapos** [comment] 2020-07-14 12:44
Duplicate of: https://github.com/elastic/apm-agent-dotnet/issues/688

This is not a high effort issue, I'll add it and try to target it with the next release.

**Comment by gregkalapos** [comment] 2020-07-15 20:49
I started working on this in https://github.com/elastic/apm-agent-dotnet/pull/904 - closing this now. https://github.com/elastic/apm-agent-dotnet/issues/688 remains open as long as the PR is not merged.

**Closed by gregkalapos** 2020-07-15 20:49 UTC
Labels: enhancement
