### ISSUE TITLE
.Net Core 3.1 / Problem with PerformanceCounter

### ISSUE THREAD

**Issue by iqmeta** [elastic/apm-agent-dotnet#682] opened 2020-01-08 08:02 UTC
Hi,

just got the Client to work with Core 3.1, but I had to remove
the SystemTotalCpuProvider.

Looks like there is a Problem with the PerformanceCounter.

The whole agent hangs on / deadlocks on this line preventing further startup.

Elastic.Apm.Metrics.MetricsProvider.SystemTotalCpuProvider
`_processorTimePerfCounter = new PerformanceCounter("Processor", "% Processor Time", "_Total");
`

Cheers Otto.

**Comment by gregkalapos** [comment] 2020-01-08 19:32
Hi @iqmeta,

thanks for reporting this.

Unfortunately I was unable to reproduce the problem. Can you share a bit more details about your environment and about your application? 

What Windows version did you try it on? Does it always reproduce - e.g. with a brand new project, too? If not would it be possible to give us a small reproducer? 

I tried an ASP.NET Core 3.1 app:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.2.0" />
  </ItemGroup>
</Project>
```

With only .NET Core 3.1 on the machine:

```
C:\>dotnet --version
3.1.100

C:\>dotnet --list-sdks
3.1.100 [C:\Program Files\dotnet\sdk]
```

But that does not reproduce the problem - all works fine.

Based on what you say, I'm not yet sure how can we proceed here, a reproducer would really help. If the app hangs in the `PerformanceCounter` constructor, then maybe one way would be to also push the metrics initialization to the background thread that captures the metrics, but that would just be a workaround, because that would then make the metrics thread hang (but at least the app would continue running).

Ultimately if this really hangs in `PerformanceCounter`, then I'd dig deeper and see what happens in that library - the call to `new PerformanceCounter("Processor", "% Processor Time", "_Total")` is guarded by a try catch block, so if the perf. counter is not available or does not work it should throw an exception and the agent would be able to handle that. 

cc @derbl4ck

**Comment by iqmeta** [comment] 2020-01-15 12:31
Hi,

sorry for the late answer. Something to do with the Processor Metrics. Maybe because we use Citrix VDI (vmware esx or xen underneath - not sure what hypervisor they use currently).

```
//WORKS
_processorTimePerfCounter = new PerformanceCounter();
// HANGS FOREVER
_processorTimePerfCounter = new PerformanceCounter("Processor", "% Processor Time", "_Total");
// NEVER REACHED
Console.WriteLine("HELLO?");
```

So the try catch does not help, because it stays inside:
`PerformanceCounter("Processor", "% Processor Time", "_Total");
`

```
Visual Studio 2019 16.4.3 / IIS Express 10.0.18362.1 (IIS_EXPRESS.180904-1626)

dotnet --version:
3.1.100

dotnet --list-sdks:
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.1.500 [C:\Program Files\dotnet\sdk]
2.1.505 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.2.104 [C:\Program Files\dotnet\sdk]
3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]
3.1.100 [C:\Program Files\dotnet\sdk]
```
Looks a bit like this:
https://github.com/Particular/NServiceBus/issues/2047

![2020-01-15 12_53_19-APMTest - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/7533842/72433854-8ee3b380-379a-11ea-8c84-9ae938e6889e.jpg)

Any idea how to get deeper because it's in System.Diagnostics.

Kind regards. Otto.

**Comment by SergeyKleyman** [comment] 2020-01-16 08:34
As a quick workaround you can try setting [`MetricsInterval`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-reporter.html#config-metrics-interval) to 0 - this should disable all metrics collection.

The main cons of the above workaround is that it will disable all the metrics - including the ones that don't rely on Performance Counters. As a better solution we might consider implementing `DisableMetrics` ([here](https://www.elastic.co/guide/en/apm/agent/java/current/config-reporter.html#config-disable-metrics) is the documentation for this configuration option in Java agent).

**Comment by gregkalapos** [comment] 2020-01-28 20:49
Hi @iqmeta, 

I opened https://github.com/elastic/apm-agent-dotnet/pull/709 to implement the `DisableMetrics` config mentioned above. 

Once that PR lands you can simply add `system.cpu.total.norm.pct` to that setting. With this the agent won't try to query the performance counter.

Now, of course this still will be a workaround, but at least you will have all other metrics. By looking at linked issues I'd say this seems to be an environmental issue, and that'd not be the first one I see with PerfCounters. Instead of debugging it, long term I'd rather investigate other options to get this metric. 

Would you be ok with closing this and following #709 and apply that once we release the `DisableMetrics` config?

**Comment by ScottKaye** [comment] 2020-02-03 15:09
I am also running into this issue using the FullFramework package.  Using the standard ASP.NET MVC template created by Visual Studio with the APM packages running locally, I'm also seeing it hang indefinitely on `new PerformanceCounter("Processor", "% Processor Time", "_Total");` in SystemTotalCpuProvider.cs.

What has worked for me is changing from IIS Express to full IIS.  I'm not sure why this is, though.

**Comment by gregkalapos** [comment] 2020-02-04 21:37
Thanks for reporting @ScottKaye.

I think the best would be to find another way to capture these values. PerCounters have many problems. 

I opened #715 for further research on what alternatives we could use. 

I close this issue, the next agent version will have a setting to turn this metrics off as a workaround, hopefully in #715 there will be a final fix.

**Closed by gregkalapos** 2020-02-04 21:37 UTC
Labels: enhancement
