### ISSUE TITLE
Increased CPU usage due to EnhancedStackFrame

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1099] opened 2020-12-18 18:38 UTC
From https://github.com/elastic/apm-agent-dotnet/issues/1039

With version `1.7.0` the agent has higher CPU usage. Seems to be caused by GC - and increased allocation seems to be caused by `EnhancedStackFrame`.

Plan: let's see if we can improve the stack trace demystifying logic to allocate less.

**Comment by kbalys** [comment] 2021-07-02 13:37
Hi, I don't know if this is correlated but we identified higher CPU usage in 1.10. The issue is raised here: https://discuss.elastic.co/t/performance-degradation-after-update-from-1-7-1-to-1-10/277552

Maybe using Ben.Demistyfier is to blame in version 1.10?

**Comment by stevejgordon** [comment] 2024-11-11 11:46
Closing as this relates to an old version of the agent, and a lot has changed. We can open a fresh issue is we have evidence that this is still a potential issue.

**Closed by stevejgordon** 2024-11-11 11:46 UTC
Labels: agent-dotnet
