### ISSUE TITLE
[BUG] Possible memory leak on AspNetCoreDiagnosticListener 

### ISSUE THREAD

**Issue by nugroho-exp** [elastic/apm-agent-dotnet#1676] opened 2022-04-08 16:20 UTC
### APM Agent version
1.14.1

### Environment

**Operating system and version:**
Linux (dockerized)

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) :
.NET 6

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):
net6.0

SpanCompression is enabled.

### Describe the bug
Our application memory keeps growing and ended up with OutOfMemoryException error.

Please see the attached dotMemory screenshot. It looks like AspNetCoreDiagnosticListener consume 695MB in _processingRequests and does not release it.  

![image](https://user-images.githubusercontent.com/35025861/162481418-394e11b2-470d-46b3-a7a0-ac4b52f7389f.png)

Created dashboard using TSVB from APM metrics

![image](https://user-images.githubusercontent.com/35025861/162482081-3ff8f7bc-c3cb-4514-992c-047f19626fc6.png)

Could you please check.

Thank you.
Nugroho

**Comment by gregkalapos** [comment] 2022-04-11 07:50
Hi @nugroho-exp 

thanks for reporting. Do you have agent logs for this? Based on the memdump it looks like transactions never end - there is a theoretical possibility for this in the code, but so far I did not thought this could happen. If you could attach agent logs on trace level, we'd know more about these transactions.

**Comment by nugroho-exp** [comment] 2022-04-15 18:03
Hi @gregkalapos. Please find the attached agent log.

[dotnet_memoryleak_debug.zip](https://github.com/elastic/apm-agent-dotnet/files/8497369/dotnet_memoryleak_debug.zip)

**Comment by gregkalapos** [comment] 2022-04-20 18:44
Thanks for the logs @nugroho-exp 

Unfortunately I wasn't really able to read out much of it. There were useful things in it, but it does not 100% verify my theory.

Nevertheless I opened https://github.com/elastic/apm-agent-dotnet/pull/1685 which I believe will fix this. That PR is merged and it'll be included in the next release. I'll keep this issue open; if possible could you please verify that the memory issue goes away, once the next release is out?

**Comment by nugroho-exp** [comment] 2022-04-21 07:09
Thanks @gregkalapos, will try it once it is released.

**Comment by nugroho-exp** [comment] 2022-05-03 07:29
Hi @gregkalapos, When will the fix be released? Thank you.

**Comment by gregkalapos** [comment] 2022-05-12 20:13
Hi @nugroho-exp, a release with the fix is out: https://github.com/elastic/apm-agent-dotnet/releases/tag/v1.15.0

Could you maybe give it a try and let me know if the issue is really fixed? Thanks.

**Comment by gregkalapos** [comment] 2022-05-24 06:48
Closing now, feel free to report here if something is not ok. The issue should be fixed.

**Closed by gregkalapos** 2022-05-24 06:48 UTC
Labels: bug, agent-dotnet
