### ISSUE TITLE
Object Reference after updating 1.8.1 -> 1.9 (Elastic.Apm.Agent.Tracer is null)

### ISSUE THREAD

**Issue by insanity13** [elastic/apm-agent-dotnet#1254] opened 2021-04-09 06:45 UTC
### APM Agent version
Elastic.Apm 1.9.

### Environment
Windows
.Net Framework 4.7.2

### Describe the bug
It looks like Elastic.Apm.Agent.Tracer behavior changed in 1.9 (previously was 1.8.1)
In DEBUG mode (local execution) we don't Initialize APM.
After updating the assembly Elastic.Apm.Agent.Tracer became null

For example, we have an Object reference
1. Windows Service 
` var transaction = Elastic.Apm.Agent.Tracer.StartTransaction(FullName, ApiConstants.TypeRequest);`
2. WebSite in APM SQL Interceptor
![image](https://user-images.githubusercontent.com/1174911/114139374-05308080-9920-11eb-9168-cfd4cf56d6b0.png)

It is not critical, I've fixed it all on our side. This Issue FYI only, feel free to close it.

**Comment by iqmeta** [comment] 2021-04-19 15:14
Same here, new Version broke existing code.
![image](https://user-images.githubusercontent.com/7533842/115259888-91b61c80-a132-11eb-915f-1c49fc5d9035.png)

**Comment by iqmeta** [comment] 2021-04-19 15:16
> It is not critical, I've fixed it all on our side. This Issue FYI only, feel free to close it.

What did you change for Debug? Also .NET 4.8 Framework? Here it's a Console Application.

**Comment by russcam** [comment] 2021-04-20 00:22
Thanks for opening @insanity13. We'll need to investigate what caused this and look to fix it

**Comment by russcam** [comment] 2021-04-20 00:42
I've put together a simple `net472` console application using Elastic.Apm 1.9.0

```c#
using System;
using Elastic.Apm;

namespace ApmAgentGitHub1254
{
    class Program
    {
        static void Main(string[] args)
        {
            var transaction = Agent.Tracer.StartTransaction("foo", "bar");
            transaction.End();
        }
    }
}
```

But I'm unable to replicate the null reference exception. @insanity13 or @iqmeta, are you able to replicate the exception with a simple example?

**Comment by iqmeta** [comment] 2021-04-20 05:00
> I've put together a simple `net472` console application using Elastic.Apm 1.9.0
> 
> ```cs
> using System;
> using Elastic.Apm;
> 
> namespace ApmAgentGitHub1254
> {
>     class Program
>     {
>         static void Main(string[] args)
>         {
>             var transaction = Agent.Tracer.StartTransaction("foo", "bar");
>             transaction.End();
>         }
>     }
> }
> ```
> 
> But I'm unable to replicate the null reference exception. @insanity13 or @iqmeta, are you able to replicate the exception with a simple example?

Sure, here a project to easy reproduce.. 
[ConsoleApp.zip](https://github.com/elastic/apm-agent-dotnet/files/6340712/ConsoleApp.zip)

Guess it's with the Agent.Setup()

Config we use like here you do in your Tests
https://github.com/elastic/apm-agent-dotnet/blob/5db57e664e5ce41498bb3b3bfea3474dd6c95d2d/test/Elastic.Apm.EntityFramework6.Tests/Ef6Tests.cs

**Comment by insanity13** [comment] 2021-04-20 05:03
I've debug my app it crashed on CentralConfigFetcher and MetricsCollector initialization.
So TracerInternal is not initialized. 
![image](https://user-images.githubusercontent.com/1174911/115338793-9c18fa80-a1b4-11eb-8052-dcf6aa9588c5.png)

I have 
```
      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
```
In my app, removed it, and it helps.

If TracerInternal initialization was earlier, or the initialization of CentralConfigFetcher would have been in the try catch, then Agent.Tracer will work.

So, maybe it is a not a good idea "The agent tries to never throw any exception".

@russcam  The main reason why didn't we see the error - is the incorrect logging:
logger is null, so if it was Logger (which is initialized as ConsoleLogger) the error was logged
![image](https://user-images.githubusercontent.com/1174911/115340016-ffa42780-a1b6-11eb-9cad-6b1ea3f7925b.png)

I think it should be fixed.

**Comment by insanity13** [comment] 2021-04-20 05:08
> Sure, here a project to easy reproduce..
Your sample works on my side (but I've changed the  framework to 4.6.1 since has no 4.6.2).

**Comment by iqmeta** [comment] 2021-04-20 05:37
> > Sure, here a project to easy reproduce..
> 
> Your sample works on my side (but I've changed the framework to 4.6.1 since I have no 4.6.2).
> 
> @iqmeta you can download 1.9 Source Code (https://github.com/elastic/apm-agent-dotnet/releases/tag/1.9.0)
> And replace Nuget Elastic.Apm by the local built library, then you can catch the exception.
> I think it'll be the fastest way to find the problem.

You're right. So I did bring in the other nuget packages...

[Test2.zip](https://github.com/elastic/apm-agent-dotnet/files/6340850/Test2.zip)

Now it fails... 
![image](https://user-images.githubusercontent.com/7533842/115342834-29efe800-a1ab-11eb-8f70-2c1d966ea749.png)

I try it also with the source myself.

**Comment by insanity13** [comment] 2021-04-20 05:42
@iqmeta you got the same issue. Check your assembly bindings
```
      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
```

**Comment by iqmeta** [comment] 2021-04-20 06:53
> @iqmeta you got the same issue. Check your assembly bindings
> 
> ```
>       <dependentAssembly>
>         <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
>       </dependentAssembly>
> ```
> 
> But I'm not sure if it can be safely removed for your application.

Yes. Thanks. Nuget Update killed it. Also think this should be fixed.

**Comment by gregkalapos** [comment] 2021-04-20 20:27
Thanks for all the info @insanity13  and @iqmeta.

> Yes. Thanks. Nuget Update killed it. Also think this should be fixed.

@iqmeta does this mean that you had the same binding redirect in place prior to updating to `1.9` and now adding it back makes it work again?

The fact that the agent initialization fails with an AssemblyLoadException due to not finding `System.ValueTuple` sounds valid and adding the dependency and using binding redirect is indeed a good fix. On the other hand, I see how this is related to the `1.9` release. 

We had this dependency previously in `1.8.1`:
![TupleDependency](https://user-images.githubusercontent.com/1091853/115459488-682aed00-a227-11eb-8df3-a8780171b80c.png)

**Comment by russcam** [comment] 2021-04-28 05:41
The reference is also there in 1.9.0

![image](https://user-images.githubusercontent.com/208231/116352160-180be600-a838-11eb-93bf-c38cfc55fb85.png)

**Comment by insanity13** [comment] 2021-04-29 08:44
@russcam I apologize for the silence. I'll investigate it next week.

p.s. I hope you haven't missed my remark on the logger?
![image](https://user-images.githubusercontent.com/1174911/116524580-99bb4c80-a8e8-11eb-9848-bdcf56e9b1cf.png)

**Comment by russcam** [comment] 2021-05-25 00:22
Thanks @insanity13, I've opened https://github.com/elastic/apm-agent-dotnet/pull/1305 to fix

**Closed** 2021-05-27 15:26 UTC
Labels: agent-dotnet, bug

**Comment by insanity13** [comment] 2021-05-28 05:43
I apologize for not respond as I promised.
I was unable to determine the update dependency on the error.
Agree you can close this Issue, thanks!
