### ISSUE TITLE
integration in .net framework owin

### ISSUE THREAD

**Issue by alfhv** [elastic/apm-agent-dotnet#586] opened 2019-11-07 20:19 UTC
I would like to have a sample or doc about how to integrate APM in a self hosted  owin webapi with .net framework 4.6.1.
app is not IIS, it is self hosted running as windows service.  
Can't go above this framework version due to limitation on other libraries.
There is a nuget package providing a Middleware (or other kind of filter) to attach APM to a IAppBuilder ?
entry point of app is like:

```
public class Startup 
{ 
        // This code configures Web API. The Startup class is specified as a type
        // parameter in the WebApp.Start method.
        public void Configuration(IAppBuilder appBuilder) 
        { 
               appBuilder.UseApm(); // ???

        }
}
```

**Comment by gregkalapos** [comment] 2019-11-07 21:46
> There is a nuget package providing a Middleware (or other kind of filter) to attach APM to a IAppBuilder ?

Unfortunately we don't have an OWIN middleware, but actually it would not be too much work to create one. 

Additionally in https://github.com/elastic/apm-agent-dotnet/issues/557 @vhatsura suggested using `DelegatingHandler` (to be honest I'm not sure that's even used in your scenario, sorry if it's off-topic, just wanted to link, since it may be relevant) - but I think for supporting OWIN a simple middleware, similar to our [`ApmMiddleware`](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.AspNetCore/ApmMiddleware.cs) (which is currently ASP.NET Core specific) would be a nice way to go.

**Comment by vhatsura** [comment] 2019-11-16 14:07
@alfhv , are you using `Microsoft.AspNet.WebApi.OwinSelfHost` package in your application?

**Comment by alfhv** [comment] 2019-11-18 10:07
Yes, exactly

Le sam. 16 nov. 2019 15:07, Vadim Hatsura <notifications@github.com> a
écrit :

**Comment by gregkalapos** [comment] 2020-03-30 20:20
This is more or less a duplicate of #557, so I'm closing this - https://github.com/elastic/apm-agent-dotnet/pull/661 already references this. So if there is more input on this, let's use #557.

**Closed by gregkalapos** 2020-03-30 20:20 UTC
