### ISSUE TITLE
1.6.0 Missing Elastic.Apm.SqlClient

### ISSUE THREAD

**Issue by chris-sung** [elastic/apm-agent-dotnet#901] opened 2020-07-10 05:24 UTC
**Describe the bug**
NuGet can't install Elastic.Apm.NetCoreAll 1.6.0 because of Elastic.Apm.SqlClient 1.6.0 not exists, but package requires it.

**Expected behavior**
Able to install Elastic.Apm.NetCoreAll 1.6.0 along with ElasticApm.SqlClient 1.6.0

**Comment by gregkalapos** [comment] 2020-07-10 08:59
Thanks for reporting! 

I uploaded `1.6.0` of `Elastic.Apm.SqlClient` to nuget.

Very likely caused by the issue which is fixed in https://github.com/elastic/apm-agent-dotnet/pull/900.

**Closed by gregkalapos** 2020-07-10 08:59 UTC
Labels: bug
