### ISSUE TITLE
Log distributed/asynchronous transaction...

### ISSUE THREAD

**Issue by nvrnight** [elastic/apm-agent-dotnet#701] opened 2020-01-21 17:12 UTC
**Is your feature request related to a problem? Please describe.**
We have many micro services, spanning different processes and they are not web APIs.

**Describe the solution you'd like**
I would like to be able to start a transaction on one application and then end it in another. This way I will have a single transaction that spans the entire processes. Currently I can do this by ending the transaction early and still using the serialized transaction string in further processes, but that makes it seem like the first transaction is finished long before it should be.

Example:
Application1:
var tx = tx.StartTransaction("foo", "bar");
...do stuff...
Pass forward Serialized Distributed Transaction String as needed for child processes
End Application 1

Applications 2 through ?
...have their own sub-transactions or maybe even just spans...

Application final
var tx = Agent.Tracer.ContinueTransaction(distributedTransactionString);
...do other stuff...
tx.End();

Also maybe even a separate API for those who don't have other stuff to do before ending the transaction: Agent.Tracer.EndTransaction(distributedTransactionString);

**Comment by gregkalapos** [comment] 2020-01-28 18:41
Hi @nvrnight 

what you describe is the concept of a trace. [Here](https://www.elastic.co/guide/en/apm/get-started/current/distributed-tracing.html) we have documentation on it - it's really worth reading that, I feel it addresses exactly the problem you describe and shows how Elastic APM solves it in the UI.

This is supported out of the box by the .NET agent in case the applications communicate over HTTP. 

If they don't communicate over HTTP you can manually transfer the trace id (that is the id that glues the together the transactions to form a trace). [This part of the .NET Agent doc](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#manually-propagating-distributed-tracing-context) describe how to use this API.

**Comment by nvrnight** [comment] 2020-01-31 04:03
@gregkalapos What you described is what I am talking about. The trace is only accurate when the transaction is synchronous on a single application. Once your try to trace something that spans multiple applications and is an asynchronous workflow it is no longer accurate.

For example in the case of 2 separate console applications. If you start a trace(transaction) in one application you cannot end it in another application. You can create a trance in the first application and also end it in that application and pass the trace id forward to the 2nd application and use that for starting and finishing a new transaction, but what that does is makes it appear that the total trace at the root level is only as long as the first application.

**Comment by gregkalapos** [comment] 2020-03-30 19:27
Hi @nvrnight,

is this still an issue? 

A couple of things:

> If you start a trace(transaction) in one application you cannot end it in another application

That is by design. The data model we use is this: A transaction represents the highest level of work you’re measuring within a service and multiple transactions form a trace. So by definition a transaction can't be started in one app and ended in another. 

Let's say we have 2 console apps (A and B)

Now, I'm not sure how synchronicity changes this. The call to B is either considered as part of the transaction that is captured in A (in other words its duration is included in the transaction captured in A) or not - I don't see why it matters if it's async or not - the duration of the operation is the same.

I guess 2 things can happen (pseudo-code):


1. A calls B and only ends the transaction once B is done
```
StartTransaction()
processB = CallB()
processB.WaitUntilFinish()
EndTransaction()
```


2. A calls B with fire-and forget
```
StartTransaction()
CallB() //FireAndForget - do not care about the result
EndTransaction()
```

In the 1. case here is how a trace looks like:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1091853/77952920-b4c62200-72cc-11ea-9a89-59ad3e0625c0.png">

So in this case the duration of Transaction2 is considered part of Transaction1.

In the 2. case here is how a trace looks like:
<img width="1831" alt="image" src="https://user-images.githubusercontent.com/1091853/77951720-c9a1b600-72ca-11ea-999f-7f93da2864ec.png">

The 1. service is the `ApiSamples` with `Transaction1` - as you can see it finishes after 1418ms, then `Transaction2` happens in Service2. `Transaction1` does not wait until `Transaction2` is finish - it just starts it and that's it. 

But still we see that the whole trace took 2244 ms with the gap in between the 2. services. Maybe 1 thing to keep in mind here is that a trace is not an event - it's just a set of transactions, so you won't have a box for that on the timeline - still as you can see on the screenshot in Kibana you can easily see how long the whole trace takes.

Now if by "asynchronous transaction" you mean something like an async method in C# then it's not something that really fits this model - in that case what the agent measures is the duration that the whole call takes (we have one flag that could be potentially used to mark it as an async call, but it's not used yet), but on the timing itself it does not make a difference - so sync or async what we measure here is the duration.

**Comment by gregkalapos** [comment] 2020-04-06 19:40
Closing now, feel free to reopen in case we need to continue the discussion.

**Closed by gregkalapos** 2020-04-06 19:40 UTC
Labels: enhancement

**Comment by christian-be** [comment] 2020-11-16 09:32
Hi @gregkalapos!

I have a similar use-case like the thread-starter in a current project of mine. I understand, that a trace itself is not an event, but I think especially for microservice-architectures, the current functionality provided by apm is lacking something. Consider the following-scenario with 3 independent services, which are communicating via a message broker (DistributedTracingData is propagated).

Service 1: Receives request via HTTP-REST, does some logging, puts it on a queue
Service 2: Pulls message from queue, processes it, and puts it on a second queue for service 3
Service 3: Finishes workflow and transmits message to an external system.

Like you showed in your post before, it is very easy to look at the traces and see how long every service takes. Since all the timing information will be only be regarding to the first transaction (like in your case 2.), it is not possible though to measure the end-to-end workflow. For example: I have the requirement, that my workflow is not allowed to take longer than 10 seconds. If I now want to register an alarm with 10s, I am not catching performance problems in my service 2 and 3, as long as my web-service is running fine. I think this is also the problem of the thread-starter.

**Comment by felixbarny** [comment] 2020-11-19 14:11
The discussion continues here: https://discuss.elastic.co/t/apm-distirubted-tracing-in-microservice-architectures/255970
