### ISSUE TITLE
[BUG] APM agent 1.18.0.0 not working on .NET 6 

### ISSUE THREAD

**Issue by karpediemnow** [elastic/apm-agent-dotnet#1904] opened 2022-11-15 13:59 UTC
### APM Agent version
The version of the `Elastic.Apm` nuget package is 1.18.0.0

### Environment
Docker image:
mcr.microsoft.com/dotnet/aspnet:6.0

Application target framework to 
net6.0

### Describe the bug

![image](https://user-images.githubusercontent.com/1301695/201936202-f3e60f85-68fc-4747-b2e1-586f6ba9a168.png)

Work correctly with elastic_apm_profiler version 1.18.0.0

**Comment by z1c0** [comment] 2022-11-15 14:13
Hi @karpediemnow,

It looks like you were using `DOTNET_STARTUP_HOOKS`, is that correct?

Did you follow [these instructions](https://www.elastic.co/guide/en/apm/agent/dotnet/master/setup-dotnet-net-core.html)?
If yes, could you follow the troubleshooting steps [described here](https://www.elastic.co/guide/en/apm/agent/dotnet/master/troubleshooting.html#startup-hook-failure) (`ELASTIC_APM_STARTUP_HOOKS_LOGGING`) and attach the logs to this issue?

**Comment by karpediemnow** [comment] 2022-11-15 20:53
Hi z1c0,
Yes I have followed the "Zero code change" instruction. 
I have auto instrumented a .net5.0 application without problems. As soon as possible I will attach  the startup logs.

**Comment by karpediemnow** [comment] 2022-11-16 08:21
this is the log:
![image](https://user-images.githubusercontent.com/1301695/202124071-2010bbde-799e-4f39-88f2-960224b6fd37.png)

this is my installation path:
![image](https://user-images.githubusercontent.com/1301695/202126311-3190e027-e976-409a-b71e-7f45d83a98dd.png)

Thanks for the support ;)

**Comment by karpediemnow** [comment] 2022-11-16 08:45
Probably in Elastic.Apm.StartupHook.Loader the running path is wrong:

![image](https://user-images.githubusercontent.com/1301695/202131446-89575d07-a441-459f-a195-2b83531dba21.png)

I have found a similar problem on stackoverflow
[stackoverflow](https://stackoverflow.com/questions/54716416/how-do-i-get-the-current-executing-directory-on-linux-with-net-core)

 Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);

**Comment by z1c0** [comment] 2022-11-16 15:43
Hi @karpediemnow,

I tried to reproduce the issue you reported, but to no avail yet.

Testing `net60` on Linux with the `DOTNET_STARTUP_HOOKS` feature is part of our regular CI tests, so we really need to have hit some obscure corner case here.

I also tested this manually with the Docker image you mentioned: `mcr.microsoft.com/dotnet/aspnet:6.0`, and the latest agent released [ElasticApmAgent_1.18.0.zip](https://github.com/elastic/apm-agent-dotnet/releases/download/v1.18.0/ElasticApmAgent_1.18.0.zip), but everything worked as expected.

The only way to reproduce the error I saw in your screenshot was to **physically remove** the `Elastic.Apm.dll` assembly from the `6.0.0` directory.

Can you double-check the contents of this directory, please?

Also, could you again check these environment variables and paths and add them to the issue:

* `DOTNET_STARTUP_HOOKS`
* `ELASTIC_APM_STARTUP_HOOKS_LOGGING``
* full path of your ASP.NET 6 application
* full path of the directory where the downloaded agent is in

**Comment by z1c0** [comment] 2022-11-17 06:39
Closed by accident, sorry.

**Comment by karpediemnow** [comment] 2022-11-17 10:06
Hi z1c0,
I have figured out the issue in my dockerfile I use 
WORKDIR /app
setting a working directory misconfigure the Assembly.GetExecutingAssembly().Location
;)

**Comment by z1c0** [comment] 2022-11-17 10:14
Hi @karpediemnow,
so it's working now for you?

**Comment by z1c0** [comment] 2022-11-21 16:19
Hi @karpediemnow,
since your last comment suggested that the problem is gone and I have not heard back otherwise, I will resolve this issue.
Feel free to reopen it, should the problem still persist.
Thank you for reaching out!

**Closed by z1c0** 2022-11-21 16:19 UTC
Labels: bug, agent-dotnet, community, triage
