### ISSUE TITLE
APM service dashboard throwing 500 errors when using APM dotnet agent 1.18 with Elastic 8.5

### ISSUE THREAD

**Issue by code-junkie-403** [elastic/apm-agent-dotnet#1899] opened 2022-11-06 22:57 UTC
### APM Agent version
The version of the `Elastic.Apm` nuget package used
1.18

### Environment

**Operating system and version:**
Loca development: macOS Ventura 13
Hosting: Azure App Service (Linux)

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) :
.NET 6

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):
net6.0

### Describe the bug
When using a Linux azure app service, Elastic APM shows the following error when viewing APM service dashboard. This works fine when running on local macOS. 

`search_phase_execution_exception: [script_exception] Reason: runtime error (500)`

Note that the same code also works with Elasticsearch 7.17 deployment. Seems the bug only affects version 8.4 and 8.5. 

### To Reproduce

1. Create a new Elastic instance on Elastic cloud. Choose version 8.5 when asked.
2. Create a .NET Web API project. I'm using the weather API sample that comes when creating a new project. 
3. Add Elastic APM 1.18 nuget package
4. Add APM config to appsettings.json
```
  "ElasticApm":
  {
    "Enabled": true,
    "ServiceName": "TestAPM",
    "SecretToken": "{Token-Here}",
    "ServerUrls": "{APM-URL}",
    "Environment": "TestAPM",
    "TransactionSampleRate": 1.0,
    "CaptureBody": "all",
    "CloudProvider": "azure"
  }
```
5. Wire up Elastic APM
```
app.UseAllElasticApm(builder.Configuration);
```
6. Create a new Azure App Service, make sure it is Linux
7. Publish the solution to Azure
8. Call the API a few times either from browser or Postman
9. Open Kibana, go to Observability > APM
10. Under APM, select services
11. Click on the service name
12. See the error popup on the service overview page

#### Expected behavior

View the APM page without error

#### Actual behavior
This error is displayed: search_phase_execution_exception: [script_exception] Reason: runtime error (500)

**Comment by z1c0** [comment] 2022-11-17 06:33
Hi @code-junkie-403,

it looks like this problem can be resolved by upgrading to `8.5.1` (see [duplicate issue](https://github.com/elastic/sdh-apm/issues/765)).
Let us know if that works for you.

CC @kpatticha

**Closed by z1c0** 2022-11-17 06:33 UTC
Labels: bug, agent-dotnet, community, triage

**Comment by oliverkane** [comment] 2022-12-21 14:36
This same issue is occurring for me today.  Exact same description, but I'm using a slightly different set of versions, all latest and greatest:
- Elastic 8.5.3, fresh install (K8s Operator, quick start defaults)
- 1.19 "All" Nuget packages. Defaults

Interestingly, I think this bug stops the agent from collecting or displaying data after that particular instance.  I only see a very small subset of the API calls I made, and they're all the very earliest I'd expect from the application, such as SignalR starting up. 

Should I open up a new Issue, or should we reopen this one and continue?  Seems like the same problem with the exception of the newer versions.

**Comment by oliverkane** [comment] 2022-12-21 14:42
```json
{"statusCode":500,"error":"Internal Server Error","message":"search_phase_execution_exception: [script_exception] Reason: runtime error","attributes":{"_inspect":[]}}
```

URL: 

http://localhost:40627/internal/apm/services/AppWeb5/service_overview_instances/main_statistics?environment=ENVIRONMENT_ALL&kuery=&latencyAggregationType=avg&start=2022-12-20T21:59:47.295Z&end=2022-12-21T14:38:47.295Z&transactionType=request&offset=1d

![image](https://user-images.githubusercontent.com/1761622/208930586-d3c54697-0733-4a15-87ce-7f6444f87ddd.png)

Kibana stack:

```txt
[2022-12-21T14:38:48.055+00:00][ERROR][plugins.apm] Error: search_phase_execution_exception: [script_exception] Reason: runtime error
    at /usr/share/kibana/x-pack/plugins/observability/common/utils/unwrap_es_response.js:59:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getServiceInstancesSystemMetricStatistics (/usr/share/kibana/x-pack/plugins/apm/server/routes/services/get_service_instances/get_service_instances_system_metric_statistics.js:136:20)
    at async Promise.all (index 1)
    at /usr/share/kibana/x-pack/plugins/apm/server/routes/services/get_service_instances/main_statistics.js:27:51
    at async Promise.all (index 0)
    at handler (/usr/share/kibana/x-pack/plugins/apm/server/routes/services/route.js:660:45)
    at /usr/share/kibana/x-pack/plugins/apm/server/routes/apm_routes/register_apm_server_routes.js:96:13
    at Router.handle (/usr/share/kibana/node_modules/@kbn/core-http-router-server-internal/target_node/src/router.js:163:30)
    at handler (/usr/share/kibana/node_modules/@kbn/core-http-router-server-internal/target_node/src/router.js:124:50)
    at exports.Manager.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at Object.internals.handler (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:371:32)
    at Request._execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:281:9)
Response: {
  error: {
    root_cause: [
      {
        type: 'script_exception',
        reason: 'runtime error',
        script_stack: [
Response: {
  error: {
    root_cause: [
      {
        type: 'script_exception',
        reason: 'runtime error',
        script_stack: [
          'org.elasticsearch.server@8.5.3/org.elasticsearch.index.fielddata.ScriptDocValues.throwIfEmpty(ScriptDocValues.java:92)',
          'org.elasticsearch.server@8.5.3/org.elasticsearch.index.fielddata.ScriptDocValues$Longs.get(ScriptDocValues.java:110)',
          'org.elasticsearch.server@8.5.3/org.elasticsearch.index.fielddata.ScriptDocValues$Longs.getValue(ScriptDocValues.java:105)',
          "total = useCgroupLimit ? doc[limitKey].value : doc['system.memory.total'].value;\n" +
            '\n' +
            '    double ',
          '                                                                         ^---- HERE'
        ],
        script: ' ...',
        lang: 'painless',
        position: { offset: 638, start: 565, end: 658 }
      }
    ],
    type: 'search_phase_execution_exception',
    reason: 'all shards failed',
    phase: 'query',
    grouped: true,
failed_shards: [
      {
        shard: 0,
        index: '.ds-metrics-apm.internal-default-2022.12.21-000001',
        node: 'zvUKs5fqTz605E-Uu81Sig',
        reason: {
          type: 'script_exception',
          reason: 'runtime error',
          script_stack: [
            'org.elasticsearch.server@8.5.3/org.elasticsearch.index.fielddata.ScriptDocValues.throwIfEmpty(ScriptDocValues.java:92)',
            'org.elasticsearch.server@8.5.3/org.elasticsearch.index.fielddata.ScriptDocValues$Longs.get(ScriptDocValues.java:110)',
            'org.elasticsearch.server@8.5.3/org.elasticsearch.index.fielddata.ScriptDocValues$Longs.getValue(ScriptDocValues.java:105)',
            "total = useCgroupLimit ? doc[limitKey].value : doc['system.memory.total'].value;\n" +
              '\n' +
              '    double ',
            '                                                                         ^---- HERE'
          ],
          script: ' ...',
          lang: 'painless',
          position: { offset: 638, start: 565, end: 658 },
          caused_by: {
            type: 'illegal_state_exception',
            reason: "A document doesn't have a value for a field! Use doc[<field>].size()==0 to check if a document is missing a field!"
          }
        }
      }
```

**Comment by oliverkane** [comment] 2022-12-21 14:44
I'm pretty new to Elastic/APM, but from what I'm seeing, it looks like the routine is looking for my system memory in the APM trace and is not finding it?

**Comment by ldn7** [comment] 2023-04-13 07:06
I have a similar problem. Anybody solved this problem? Thanks

**Comment by kpatticha** [comment] 2023-04-13 09:29
@ldn7 
We'll pull in a bug fix for 8.8 and backport it to 8.7. Does that work for you?

**Comment by ThanhPT-ITVN** [comment] 2023-10-02 09:14
Hi,

I am facing the same problem with ES 8.10.2. 
Does anyone have any solution to fix it?

Thanks.

**Comment by kpatticha** [comment] 2023-10-04 06:34
@ThanhPT-ITVN It would be helpful if we can get the following:

- a HAR file after they have enabled `bfetch:disableCompression` in Kibana / Stack Management / Advanced Settings and `observability:enableInspectEsQueries`. You can find some guidance about how to enable inspection [here](https://github.com/elastic/kibana/blob/main/x-pack/plugins/apm/dev_docs/query_debugging_in_development_and_production.md#elasticsearch-query-debugging-aka-inspector).
- the URL of the page from which the HAR has been captured
-  screenshots of the page from which the HAR has been captured.v Please make sure that the whole page is visible and an absolute time range is selected that matches both screenshots and the URL params from the HAR file.
- Any error which might be visible in the Javascript console of the browser after they reproduce the problem
