### ISSUE TITLE
Complete support for all the properties of Intake v2 request object

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#285] opened 2019-06-15 11:07 UTC
See spec at https://github.com/elastic/apm-server/blob/master/docs/spec/request.json

Currently we are missing:
- `env`
- `url.port`
- `url.hash`

**Comment by gregkalapos** [comment] 2020-03-30 20:41
Duplicate of: https://github.com/elastic/apm-agent-dotnet/issues/212

**Closed by gregkalapos** 2020-03-30 20:41 UTC
Labels: cross APM agents, technical debt
