### ISSUE TITLE
CurrentTransaction don't return null

### ISSUE THREAD

**Issue by magnayn** [elastic/apm-agent-dotnet#231] opened 2019-05-20 10:01 UTC
The java agent returns a noop transaction if there is no current transaction, which prevents having to either check or having NRE exceptions occur.

Is this intentional, or would a fix along similar lines be of use?

**Comment by gregkalapos** [comment] 2019-05-20 10:48
Long or mid term with very high probability this behaviour won’t change - at least we don't plan to do it. This behaviour is intentional.

The main reason is that in .NET we already expose a couple of things on `ITransaction` and `ISpan` that forces the user to null check. Couple of examples: `Agent.Tracer.CurrentTransaction.Context.Request`, `Agent.Tracer.CurrentTransaction.Context.Response` - we discussed if there would be a better way to do it, but the conclusion was that the most natural way to handle this in C# would be to make this nullable and document it - and this is what we did.

So the point is: we already have a couple of things on the API where you need to null-check, and the `Agent.Tracer.CurrentTransaction` follows this. The convention in the API is: when something can be null, you need a null-check. I think mixing 2 concepts could be confusion that's why we don't plan to return something different than `null` from `Agent.Tracer.CurrentTransaction` when there is no active transaction.

This is a difference between the Java and the .NET API. Also I’d like to mention that `Context` is not exposed by Java currently, so they don’t really have atm the challenge I described above.

Do you have any problem caused by this? Is there any specific issue with this, other than having a little bit of a difference between the 2 APIs?

**Comment by magnayn** [comment] 2019-05-20 11:53
Thankyou for the additional detail! 

So I'm experimenting at this stage; I'd instrumented a bit of our .net code, which is, effectively, a serialization function, as I suspect this can take some time. Something like this:

```
 Elastic.Apm.Agent.Tracer.CurrentTransaction.CaptureSpan("Serialize", "segment", (s) =>
            {
... existing code ...
}
```

This blew up when it was unexpectedly called from outside a transaction. I think the pattern is that an object is returned from my outer "transaction" into mvc.net, which then calls something on that object which ultimately triggers the serialization function, and hence the NPE. I was certainly a little surprised to find the behaviour was different given the API looks so similar (and the documentation shows the same CurrentTransaction..CaptureSpan() stanza without mentioning the risk of NPE).

If I have to check the result of CurrentTransaction, the code is going to look a bit ugly, as the closure content always needs to run regardless. I guess I can add my own extension function to do a 'CurrentOrNoop' and implement my own ITransaction/ISpan that just defers.

I suspect this may lead to bugs. That said, I also have the case where I meet code instrumented with CreateTransaction that has followed a path whereby it's already _in_ a transaction, so I might be better off abstracting "transaction management" elsewhere.

**Comment by magnayn** [comment] 2019-05-20 16:38
As an aside : is anyone actively looking at an opentracing bridge (similar to the java version) ?

I don't want to duplicate effort if there is, but it feels like I could spin something for a PoC. 

OpenTracing as an API is probably going to be politically more palatable for us..

**Comment by gregkalapos** [comment] 2019-05-20 16:51
>  (and the documentation shows the same CurrentTransaction..CaptureSpan() stanza without mentioning the risk of NPE)

It's mentioned in the documentation of [`Transaction.CurrentTransaction`](https://github.com/elastic/apm-agent-dotnet/blob/master/docs/public-api.asciidoc#transaction-currenttransaction ), nevertheless I agree that we should give this hint also in the `CaptureSpan()` part. I'll add this to the documentation - good feedback, thanks! 

> If I have to check the result of CurrentTransaction, the code is going to look a bit ugly, as the closure content always needs to run regardless. 

Yes, that's right, as an alternative, you could use the [`StartTransaction` method](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#api-start-transaction), with that it'll be probably easier to achieve this. Btw. this makes me thin that maybe we should run the lambda, regardless of the transaction 🤔  (anyway... this is currently not implemented, and I don't want to hijack this issue :) )

> As an aside : is anyone actively looking at an opentracing bridge (similar to the java version) ?

No, we don't actively work on it atm, but it's on our radar - similarly to OpenCensus, and OpenTelemetry (the new one, which is the merge of OpenTracing and OpenTelemetry), but we don't actively work on it yet. In case you want to contribute I'm happy to support you; feel free to ask questions and let me know in case you need any help.

**Comment by gregkalapos** [comment] 2019-07-01 20:00
I close this now. 

Opened #332 to adapt the docs as promised.

I think we are all ok with the API - this seems to be a difference compared to Java (we return `null`, Java returns an dummy object), but this is by design and atm we don't plan to change this.

@magnayn feel free to reopen if there is further discussion needed.

**Closed by gregkalapos** 2019-07-01 20:00 UTC
Labels: discuss, enhancement
