### ISSUE TITLE
It is recommended to add a switch to control the size of RequestBody

### ISSUE THREAD

**Issue by wajika** [elastic/apm-agent-dotnet#1372] opened 2021-08-07 05:46 UTC
[Consts.cs#L11](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.AspNetCore/Consts.cs#L11)

According to the source code, the length of RequestBody is limited to 2048 bytes, which is not enough for our service. Can the elastic team add a switch to make it unrestricted?

**Comment by russcam** [comment] 2021-08-09 07:00
Hi @wajika,

This is essentially a duplicate of https://github.com/elastic/apm-agent-dotnet/issues/1359. I'm going to close this to track in that issue.

A PR has been opened to increase to 10k, in line with the Java agent (https://github.com/elastic/apm-agent-dotnet/pull/1368). We discussed making this a centrally configurable value but haven't made a decision on this yet.

**Closed by russcam** 2021-08-09 07:00 UTC
Labels: enhancement, agent-dotnet
