### ISSUE TITLE
Request body is not captured when CaptureBody set to errors and HTTP response status >= 400

### ISSUE THREAD

**Issue by yuft** [elastic/apm-agent-dotnet#877] opened 2020-06-10 06:56 UTC
**Describe the bug**
According to the code, when HTTP response status code >= 400 and CaptureBody is set to errors, HTTP request body should be captured. But it is not.

https://github.com/elastic/apm-agent-dotnet/blob/374d799672115c2bd860b72af793ce38489ba4ac/src/Elastic.Apm.AspNetCore/ApmMiddleware.cs#L73

**To Reproduce**
1. Use this config 'CaptureBody: errors'
2. Then send a request which returns a status code >= 400
3. Then check Kibana.
4. APM=> http.request.body.original => N/A(which is null actually).

**Expected behavior**
http.request.body.original shows request body.

**More Info**

Looks like it is because the request is already Sampled before.

**Comment by DaRochaRomain** [comment] 2021-04-07 09:53
Is there a way to fix this issue? It's taking quiet some space to capture all body transaction when only errors might be needed.

**Comment by ejszi** [comment] 2021-09-21 05:49
More than one year and it still doesn't work.

**Comment by russcam** [comment] 2021-11-04 02:56
Hi @yuft, apologies for the delay in getting round to looking at this.

I ran the following:

1. the SampleAspNetCoreApp in the repository
2. set `"CaptureBody": "errors",` in appsettings.json
3. hit the `api/Home/PostError` endpoint with PowerShell (throws an exception and returns a 500 HTTP status code)

   ```ps
   Invoke-WebRequest -Method Post https://localhost:44391/api/Home/PostError -Body "foo=bar"
   ```
4. I see the request body captured in APM UI (I'm running against 7.15) for 500 response status code
 
   ![APM UI captured body for error](https://user-images.githubusercontent.com/208231/140249457-1b26cfe6-2b54-42c5-8f7e-c630192a3296.png)

5. hit the `api/Home/Post` endpoint with PowerShell (returns a 200 HTTP status code)

   ```ps
   Invoke-WebRequest -Method Post https://localhost:44391/api/Home/Post -Body "foo=bar"
   ```
6. I see the request body is not captured in APM UI (it says `[REDACTED]` which is the default value)

   ![APM UI no captured body for OK](https://user-images.githubusercontent.com/208231/140249820-4270923c-0134-4692-a8d8-4dc5ba4def39.png)

This looks to match expected behaviour, unless I misunderstand the issue. This is running on the master branch of the repository, but I don't think there have been any changes here since the [last agent release, 1.11.1](https://www.nuget.org/packages/Elastic.Apm/1.11.1), so the behaviour should be the same. Given the time between opening this issue and looking at it now, it's possible this has been fixed in the interim. Would you be able to check the behaviour with agent version 1.11.1?

**Comment by yuft** [comment] 2021-11-04 03:07
can anyone help to check? 
I have moved away from the project using Elastic APM.

**Comment by russcam** [comment] 2021-11-09 05:31
Thanks for the update, @yuft. I'm going to close this issue for now as I can't replicate it with 1.11.1. If anyone is able to reproduce the issue with version 1.11.1 or later, please feel free to reopen to discuss.

**Closed by russcam** 2021-11-09 05:31 UTC
Labels: bug

**Comment by softnrajkumar1994** [comment] 2022-11-14 09:12
i am facing this issue using 1.34.0 version
