### ISSUE TITLE
[BUG] CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode

### ISSUE THREAD

**Issue by privjimmie** [elastic/apm-agent-dotnet#1985] opened 2023-01-23 09:20 UTC
### APM Agent version
Elastic.Apm.NetCoreAll, v1.19.0

### Environment

**Operating system and version:**
Windows 11

**.NET Framework/Core name and version**
.NET 6

### Describe the bug
Adding InvariantGlobalization = true property in the project file, causes exception from the agent

_I got asked to create a issue based on this discussion thread; https://discuss.elastic.co/t/culturenotfoundexception-only-the-invariant-culture-is-supported-in-globalization-invariant-mode/323665_

### To Reproduce

1. Add InvariantGlobalization = true in your project file. Example:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<NoWarn>$(NoWarn);1591</NoWarn>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<PlatformTarget>x64</PlatformTarget>
	<InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
```

2. Run your app
3. See error

#### Expected behavior
No error/exceptions

#### Actual behavior
Exception

```
[07:21:15 ERR] {SystemTotalCpuProvider} Error instantiating 'Processor' performance counter
System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'culture')
9 (0x0009) is an invalid culture identifier.
   at System.Globalization.CultureData.GetCultureData(Int32 culture, Boolean bUseUserOverride)
   at System.Globalization.CultureInfo..ctor(Int32 culture, Boolean useUserOverride)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at Elastic.Apm.Metrics.MetricsProvider.SystemTotalCpuProvider.GetSamples()
[07:21:15 WRN] {SystemTotalCpuProvider} System metrics won't be collected
[07:21:15 WRN] {MetricsCollector} Failed reading total system CPU time 1 times: no valid samples
```

**Comment by z1c0** [comment] 2023-01-26 13:38
Hi @privjimmie,

thanks for bringing this to our attention!

The root cause for this issue is a breaking change in the .NET framework regarding *globalization-invariant mode* (see [here](https://learn.microsoft.com/en-us/dotnet/core/compatibility/globalization/6.0/culture-creation-invariant-mode)).
This change affected the behavior of `PerformanceCounter`, where an instance of `CultureInfo` was created in a no-longer-supported way. This was fixed in .NET with the following [PR](https://github.com/dotnet/runtime/pull/65537).
(**Note** that early versions of .NET 6 still have the problematic code but that fix above was ported to .NET `6.0.4`).

Unfortunately, `Elastic.Apm` is currently referencing version `4.5.0` of `System.Diagnostics.PerformanceCounter` where the .NET bug is still present.

**How to fix this:**

* As a (temporary) workaround, you can set an explicit reference to a recent version of  `System.Diagnostics.PerformanceCounter`  in your application
  * e.g. `<PackageReference Include="System.Diagnostics.PerformanceCounter" Version="7.0.0" />`
* Furthermore, this behavior will be fixed in the upcoming agent release.

**Comment by privjimmie** [comment] 2023-01-27 07:34
thank you @z1c0 for a detailed report and workaround

**Closed** 2023-02-21 09:42 UTC
Labels: bug, agent-dotnet, community, triage

**Comment by Zylvian** [comment] 2023-11-01 02:34
Hi.

I am attempting to host a .NET 7 web app in a docker container on a Debian server, and this issue still persists. Has this bug been reintroduced, or perhaps not fixed in .NET 7? 

Will attempt the System.Diagnostics.PerformanceCounter workaround on my next build, but am curious as to why this issue persist, if fixed in an earlier agent.
Thanks!
