### ISSUE TITLE
When using option EnableSensitiveDataLogging from EF, sql parameters are not logged in apm

### ISSUE THREAD

**Issue by dicaetano** [elastic/apm-agent-dotnet#1340] opened 2021-06-15 13:39 UTC
When using EnableSensitiveDataLogging in EF, SQL parameters are logged to console, but the apm agent does not include this in the db span. Looking at the code in `Elastic.Apm.Model.DbSpanCommon.EndSpan`, only the CommandText is logged. 

Is there a reason for that, or its just not implemented?

**Comment by gregkalapos** [comment] 2021-06-21 10:07
This is known and it's by design. At this point we don't capture bind values in sql statements.

There is an open issue to discuss this: https://github.com/elastic/apm/issues/220

There is not much progress on this, so for short and mid term likely this won't change.

**Comment by gregkalapos** [comment] 2021-06-23 12:14
Closing for now - if there is progress on https://github.com/elastic/apm/issues/220 we may do this later.

**Closed by gregkalapos** 2021-06-23 12:14 UTC
Labels: agent-dotnet
