### ISSUE TITLE
Opentracing bridge does not support dotnet

### ISSUE THREAD

**Issue by DR9885** [elastic/apm-agent-dotnet#776] opened 2020-03-19 00:48 UTC
**Describe the feature**:
Currently we want to use OpenTracing with APM & C#, but it seems like there is no dotnet support yet. 

REF: https://www.elastic.co/guide/en/apm/get-started/current/opentracing.html

**Comment by gregkalapos** [comment] 2020-03-19 11:28
Duplicate of https://github.com/elastic/apm-agent-dotnet/issues/303

**Closed by gregkalapos** 2020-03-19 11:28 UTC
