### ISSUE TITLE
Azure ServiceBus instrumentation causing recursion errors.

### ISSUE THREAD

**Issue by sluebbert** [elastic/apm-agent-dotnet#2313] opened 2024-03-21 20:28 UTC
### APM Agent version
1.26.0 and earlier versions.

### Environment

**Operating system and version:**
Windows 11 and Linux

**.NET Framework/Core name and version** (e.g. .NET 4.6.2, NET Core 3.1.100) : 
.net 8.0

**Application Target Framework(s)** (e.g. net462, netcoreapp3.1):
net8.0

### Describe the bug
The Azure ServiceBus instrumentation appears to be causing recursion issues in Kibana when displaying spans for a sent message.

The closest related issue I could find for this was https://github.com/elastic/kibana/issues/167505 which lead me to dig into the span parent IDs.
We have many other instrumented services, most not sending Azure ServiceBus messages which do not encounter this issue. The few services that do send to the ServiceBus, do have this UI error in Kibana.

### To Reproduce

1. Add a reference to the Azure.Messaging.ServiceBus Nuget package. We are using 7.17.2.
2. Create a ServiceBusClient and use that to create a ServiceBusSender for a topic.
3. Within a transaction, use the ServiceBusSender to send a ServiceBusMessage with SendMessageAsync().
4. See recursion errors in Kibana APM transaction view when viewing the transaction.
    ![image](https://github.com/elastic/apm-agent-dotnet/assets/26212400/19571fc1-1913-49a5-af80-a41bc405346c)
5. See spans referencing themselves as the parent in Discover view.
    ![image](https://github.com/elastic/apm-agent-dotnet/assets/26212400/b2d49ef2-10d2-4f57-b3de-cd08e674e143)

#### Expected behavior
To be able to see the transaction in Kibana without recursion errors.

#### Actual behavior
Recursion errors.

**Comment by stevejgordon** [comment] 2024-11-11 15:47
@sluebbert, sorry for the lack of response. We fixed what I suspect is the cause in #2455 and released that under 1.30. We have one further bug fix that will go into 1.31 very soon. I'll let you know when that's available and we can hopefully confirm if this fixes your issue here.

**Comment by stevejgordon** [comment] 2024-11-20 08:42
Closing as fixed. 1.30.1 includes the final fix.

**Closed by stevejgordon** 2024-11-20 08:42 UTC
Labels: bug, agent-dotnet, community
