### ISSUE TITLE
Tracing

### ISSUE THREAD

**Issue by mhensen** [elastic/apm-agent-dotnet#91] opened 2019-02-04 19:12 UTC
I have the APM up and running in my kubernetes environment with the use of global variables..
So thanks again for that explanation.. Very happy with it!!!

But now the next step, 
How to activate tracing.. or how do activate tracing in my code.., what do I need to get them filled.. 
I looked at the samples but that bring me any steps closer. 

Sorry if I might have missed it somewhere..

with kind regards

**Comment by gregkalapos** [comment] 2019-02-05 17:49
Hi @mhensen, 

happy to hear that the solution with the environment variables worked! 

What kind of application do you have? 

If it's ASP.NET Core then you should already have tracing out of the box, once you added `app.UseElasticApm();` to the `Configure(IApplicationBuilder app, IHostingEnvironment env)` in the `Startup.cs` file. - If that's not the case then something is wrong...

If it's not ASP.NET Core then you have to use the [Public Agent API](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html) and start the transactions manually. (Btw. this documentation was published yesterday :) ). Does that help?

**Comment by mhensen** [comment] 2019-02-05 17:59
It is a asp.net core app v2.2 but then there is something wrong.. I have no tracing as far as I can see. 

Is there a breakpoint I can set somewhere to see if it is sent to the right address? 

 

Met vriendelijk groet,

 

Michael Hensen

WebVize BV

Verzetslaan 120

1318 BZ, Almere

06 454 60 482

**Comment by gregkalapos** [comment] 2019-02-05 18:34
What server version do you use? 

I should have said that: the agent won't work with the master and 7.0 server version in its current stage. 6.6.x and 6.5.x and 6.4.x should be ok, but master (or 7.x) won't work. - I'm saying this, because metrics was introduced I think either in 7.0 or 6.6. (I'm not sure which one).

Regarding where to debug: I'd set breakpoints in the `PayloadSender.cs` file, into the `QueuePayload` method (it's a 1 liner), if that's called then the transaction is captured, but sending fails (this is what I suspect and probably the root cause is that the server is too new (aka master)), if it doesn't get called then it already fails capturing the transaction (in this case we'll have to look further).

Also I'd set the debug level (environment variable: ELASTIC_APM_LOG_LEVEL) to `Debug`. The agent currently logs to the console...I'd check if there is something there. 

Additionally it's also worth looking at the server logs.

**Comment by mhensen** [comment] 2019-02-05 18:42
Ok thanks.. 

 

I am on Kestrel running on Ubuntu .. perhaps that could be the issue.. 
I’ll try and figure out what I can find and let you know..

**Comment by gregkalapos** [comment] 2019-02-13 16:29
@mhensen I close this now. 

We just released the first preview and here is a blogpost with a video walkthrough about how this should work: https://www.elastic.co/blog/elastic-apm-dot-net-agent-preview-released

In case you think you ran into a bug, feel free to reopen with more details.

**Closed by gregkalapos** 2019-02-13 16:29 UTC
Labels: [zube]: In Progress
