### ISSUE TITLE
Investigate streaming transport

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-dotnet#405] opened 2019-07-24 12:17 UTC
PayloadSenderV2 currently implements a batching transport: once enough events are queued they are sent as an HTTP request.

We should investigate the implementation of a streaming approach, as described in https://github.com/elastic/apm/blob/master/docs/agent-development.md#batchingstreaming-data.

In short we would start a request with chunked encoding as soon as an event is enqueued, and then continue encoding events to the request stream until a given amount of data has been sent, or the request has been active for a given amount of time.

**Comment by SergeyKleyman** [comment] 2019-07-24 13:17
We already have the issue for this - https://github.com/elastic/apm-agent-dotnet/issues/366

**Comment by SergeyKleyman** [comment] 2019-07-24 13:26
Duplicate of https://github.com/elastic/apm-agent-dotnet/issues/366

**Closed by SergeyKleyman** 2019-07-24 13:26 UTC
